# -*- restclient -*-
:host = localhost
:port = 5001
:protocol = http
:path-prefix = api

# GET "/"
GET :protocol://:host::port/:path-prefix/up

# create king
POST :protocol://:host::port/:path-prefix/king
Content-Type: application/json

{
  "name": "test king",
  "email": "test3@example.com",
  "nick": "testnick3",
  "password": "sekrit"
}
# success:
# 200
# {
#   "king": {
#     "6": {
#       "id": 6,
#       "name": "test king",
#       "nick": "testnick3"
#     }
#   }
# }
#
#
# read king
GET  :protocol://:host::port/:path-prefix/king/6
# success:
# 200
# {
#   "king": {
#     "6": {
#       "id": 6,
#       "name": "test king",
#       "nick": "testnick3"
#     }
#   }
# }
#
# failure:
# 404
# {
#   "error": "king 6 not found"
# }
#
#
PATCH :protocol://:host::port/:path-prefix/king/6
Content-Type: application/json

{
  "name": "updated name",
  "email": "updated-email1@example.com",
  "nick": "updated_nick1",
  "password": "updated secrit"
}
# success: 200
# {
#   "king": {
#     "6": {
#       "id": 6,
#       "name": "updated name",
#       "nick": "updated_nick1"
#     }
#   }
# }
#
# failure, king not found
# 404 not found
# {
#   "error": "king 6 not found"
# }
#
#
DELETE :protocol://:host::port/:path-prefix/king/5
# success:
# 200
# {
#   "message": "deleted king 5 successfully"
# }
#
# failure: king not found
# 404
# {
#   "error": "king 5 not found"
# }
