"""create user table

Revision ID: ef716046894c

Create Date: 2024-12-17 16:20:43.134845

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef716046894c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "password_hash", sa.String(length=255), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("user"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
