"""db init


Revision ID: 554533a25444
Revises: 
Create Date: 2025-01-03 09:30:56.461439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554533a25444'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('king',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nick'),
    schema='where_da_gas_at'
    )
    op.create_table('station',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='where_da_gas_at'
    )
    op.create_table('king_station',
    sa.Column('king_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['king_id'], ['where_da_gas_at.king.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['where_da_gas_at.station.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('king_id', 'station_id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('king_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['king_id'], ['where_da_gas_at.king.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['where_da_gas_at.station.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='where_da_gas_at'
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('king_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['king_id'], ['where_da_gas_at.king.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['where_da_gas_at.station.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='where_da_gas_at'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review', schema='where_da_gas_at')
    op.drop_table('price', schema='where_da_gas_at')
    op.drop_table('king_station')
    op.drop_table('station', schema='where_da_gas_at')
    op.drop_table('king', schema='where_da_gas_at')
    # ### end Alembic commands ###
