"""add primary_key to id column in price

Revision ID: 895e5a3b77ae
Revises: 6ca1768412f7
Create Date: 2024-12-18 18:23:39.422073

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "895e5a3b77ae"
down_revision = "6ca1768412f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("fuel_type", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["station.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price")
    # ### end Alembic commands ###
