"""add foreign key delete cascades

Revision ID: 956865577ea7
Revises: 895e5a3b77ae
Create Date: 2024-12-19 23:58:14.323996

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "956865577ea7"
down_revision = "895e5a3b77ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price", schema=None) as batch_op:
        batch_op.drop_constraint(
            "price_station_id_fkey", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "price_user_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None,
            "user",
            ["user_id"],
            ["id"],
            referent_schema="where_da_gas_at",
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            None,
            "station",
            ["station_id"],
            ["id"],
            referent_schema="where_da_gas_at",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("review", schema=None) as batch_op:
        batch_op.drop_constraint(
            "review_station_id_fkey", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "review_user_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None,
            "user",
            ["user_id"],
            ["id"],
            referent_schema="where_da_gas_at",
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            None,
            "station",
            ["station_id"],
            ["id"],
            referent_schema="where_da_gas_at",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("station", schema=None) as batch_op:
        batch_op.drop_constraint(
            "station_user_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None,
            "user",
            ["user_id"],
            ["id"],
            referent_schema="where_da_gas_at",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("station", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "station_user_id_fkey", "user", ["user_id"], ["id"]
        )

    with op.batch_alter_table("review", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "review_user_id_fkey", "user", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "review_station_id_fkey",
            "station",
            ["station_id"],
            ["id"],
        )

    with op.batch_alter_table("price", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "price_user_id_fkey", "user", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "price_station_id_fkey", "station", ["station_id"], ["id"]
        )

    # ### end Alembic commands ###
