"""init db

Revision ID: bcfaa9b81bc5
Revises: 
Create Date: 2024-12-24 20:17:44.872149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfaa9b81bc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user'),
    schema='where_da_gas_at'
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('location_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['where_da_gas_at.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='where_da_gas_at'
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['where_da_gas_at.station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['where_da_gas_at.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='where_da_gas_at'
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['where_da_gas_at.station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['where_da_gas_at.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='where_da_gas_at'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review', schema='where_da_gas_at')
    op.drop_table('price', schema='where_da_gas_at')
    op.drop_table('station', schema='where_da_gas_at')
    op.drop_table('user', schema='where_da_gas_at')
    # ### end Alembic commands ###
